### ISSUE TITLE
Devices disconnected

### ISSUE THREAD

**Issue by LionMike** [Galveston01/tuya-adapter#20]
All my Tuya devices disconnected. disabling then enabling adapter did nothing. Rebooted Gateway, still disconnected. Here is log info:

2020-10-14 19:45:43.546 ERROR  : tuya-adapter: { Error: Cannot find module 'p-queue'
2020-10-14 19:45:43.550 ERROR  : tuya-adapter:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2020-10-14 19:45:43.554 ERROR  : tuya-adapter:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2020-10-14 19:45:43.558 ERROR  : tuya-adapter:     at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-14 19:45:43.563 ERROR  : tuya-adapter:     at require (internal/modules/cjs/helpers.js:25:18)
2020-10-14 19:45:43.568 ERROR  : tuya-adapter:     at Object.<anonymous> (/home/pi/.mozilla-iot/addons/tuya-adapter/node_modules/tuyapi/index.js:7:27)
2020-10-14 19:45:43.572 ERROR  : tuya-adapter:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2020-10-14 19:45:43.582 ERROR  : tuya-adapter:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-10-14 19:45:43.587 ERROR  : tuya-adapter:     at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-14 19:45:43.592 ERROR  : tuya-adapter:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-10-14 19:45:43.595 ERROR  : tuya-adapter:     at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }

**Comment by bewee** [comment]
Hi @LionMike,

all add-ons had to be moved away from the Mozilla Server. That required me to create a new release. Your gateway seems to have updated the tuya add-on to the latest release, which seems to lack some dependency...
Unfortunately, I have no access to any tuya device for the next week or so... May you therefore connect to your pi and manually install the fix?
```
cd /home/pi/.mozilla-iot/addons
rm -R tuya-adapter
git clone -b fixdependencies https://github.com/Galveston01/tuya-adapter.git
```
And report back whether with this version everything works well again? If so, I can create a new release for the add-on list.

Regards

**Comment by LionMike** [comment]
Thanks for the reply. It will be several hours before I can do this.

**Comment by LionMike** [comment]
That did not work. . .

**Comment by bewee** [comment]
Hi @LionMike,

in order to help you, I need a litte more information than just "did not work" ;)
Still the same error or a new one? And when does this error even occur? Immediately after starting the add-on or rather during use?

I have packed the fix and if you have some time you could try extracting [this](https://drive.google.com/file/d/1JuPWsMYQMQwMvKWHEPfpoqstPMss7VHo/view?usp=sharing) archieve to a folder called "tuya-adapter" into the addons directory.

Alternatively, you could manually extract the the [old version](https://drive.google.com/file/d/1LZTXycKInjt4tAe4BXxI93lSvIXJ7daA/view?usp=sharing) 0.2.1 into a folder called "tuya-adapter" and use that one until I have access to a tuya device again and can have a look at the problem myself.

Regards :)

**Comment by LionMike** [comment]
Here is log info. After following the steps outlined above, I restarted the gateway and devices were still disconnected, I will work on it today.

2020-10-15 18:43:42.498 INFO   : tuya-adapter: Loading add-on tuya-adapter from /home/pi/.mozilla-iot/addons/tuya-adapter
2020-10-15 18:43:42.515 ERROR  : tuya-adapter: { Error: Cannot find module 'tuyapi'
2020-10-15 18:43:42.517 ERROR  : tuya-adapter:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2020-10-15 18:43:42.519 ERROR  : tuya-adapter:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2020-10-15 18:43:42.521 ERROR  : tuya-adapter:     at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-15 18:43:42.523 ERROR  : tuya-adapter:     at require (internal/modules/cjs/helpers.js:25:18)
2020-10-15 18:43:42.524 ERROR  : tuya-adapter:     at Object.<anonymous> (/home/pi/.mozilla-iot/addons/tuya-adapter/lib/devices/tuya-device.js:4:16)
2020-10-15 18:43:42.526 ERROR  : tuya-adapter:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2020-10-15 18:43:42.527 ERROR  : tuya-adapter:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-10-15 18:43:42.529 ERROR  : tuya-adapter:     at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-15 18:43:42.530 ERROR  : tuya-adapter:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-10-15 18:43:42.532 ERROR  : tuya-adapter:     at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }

**Comment by bewee** [comment]
Hi @LionMike,

Yeah, again the dependencies (which are now missing completely since you cloned the repository from git, I should have thought of that)... Running `npm i` in the tuya-adater directory should fix it (at least the missing tuyapi dependency)

> Error: Cannot find module 'tuyapi'

Regards :)

**Comment by LionMike** [comment]
Thanks. I will try that. Update: That fixed it. Thank you for your help. 
Closing issue.

**Comment by bewee** [comment]
@LionMike May I ask which of these did the job?

**Comment by LionMike** [comment]
Running npm i in the tuya-adapter directory solved the problem.
