### ISSUE TITLE
Error: Plugin returns the error Cannot find module 'p-queue'

### ISSUE THREAD

**Issue by wichopy** [Galveston01/tuya-adapter#22]
I installed the addon and am receiving this error as a toast when leaving the addons page in the gateway webapp.

Stack track from systemctl:
```
Oct 17 13:16:55 gateway run-app.sh[24723]: 2020-10-17 13:16:55.920 ERROR  : tuya-adapter:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
Oct 17 13:16:55 gateway run-app.sh[24723]: 2020-10-17 13:16:55.925 ERROR  : tuya-adapter:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
Oct 17 13:16:55 gateway run-app.sh[24723]: 2020-10-17 13:16:55.929 ERROR  : tuya-adapter:     at Module.require (internal/modules/cjs/loader.js:692:17)
Oct 17 13:16:55 gateway run-app.sh[24723]: 2020-10-17 13:16:55.932 ERROR  : tuya-adapter:     at require (internal/modules/cjs/helpers.js:25:18)
Oct 17 13:16:55 gateway run-app.sh[24723]: 2020-10-17 13:16:55.934 ERROR  : tuya-adapter:     at Object.<anonymous> (/home/pi/.mozilla-iot/addons/tuya-adapter/node_modules/tuyapi/index.js:7:27)
Oct 17 13:16:55 gateway run-app.sh[24723]: 2020-10-17 13:16:55.936 ERROR  : tuya-adapter:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Oct 17 13:16:55 gateway run-app.sh[24723]: 2020-10-17 13:16:55.939 ERROR  : tuya-adapter:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Oct 17 13:16:55 gateway run-app.sh[24723]: 2020-10-17 13:16:55.941 ERROR  : tuya-adapter:     at Module.load (internal/modules/cjs/loader.js:653:32)
Oct 17 13:16:55 gateway run-app.sh[24723]: 2020-10-17 13:16:55.943 ERROR  : tuya-adapter:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Oct 17 13:16:55 gateway run-app.sh[24723]: 2020-10-17 13:16:55.946 ERROR  : tuya-adapter:     at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
```

Addon version: 0.2.2
Gateway version  (from package.json, dont know how to find it in the web app) 0.12.0

**Comment by bewee** [comment]
Hi @wichopy,

I'm aware of this problem (#20): a dependency is missing in the packed release 0.2.2. I have therefore created a new release (0.2.3) which fixes the described issue and which should be available through the add-on list soon.

Regards :)

**Comment by bewee** [comment]
@wichopy New release is now on the add-on list. Could you please close this issue if everything works fine for you now? Thanks :)

**Comment by wichopy** [comment]
That was quick!  Will test it out soon

**Comment by wichopy** [comment]
The gateway auto updated to version 0.2.3 and the addon now runs and I can see my devices :)

Will close this issue.
